Docs: Change zeit to vercel
vuejs/vue-cli pull request #5807
Opened 2020-08-20 03:29 UTC by FFRaycoder

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
只是将zeit改为Vercel

2020-08-27 03:40 UTC, sodatea requested changes
谢谢帮助！

另外还请把英文文档的相应部分也一并更新一下吧，这样其他语言的文档翻译者看到后能方便跟进

2020-08-27 03:40 UTC, sodatea commented on docs/zh/guide/deployment.md
>  npm install -g now
```suggestion
npm install -g vercel
```
这里也要改一下

2020-08-27 09:56 UTC, FFRaycoder commented on docs/zh/guide/deployment.md
>  npm install -g now
好的，我去修改一下

2020-08-28 05:43 UTC, sodatea approved these changes

2020-08-28 05:44 UTC, merged