Update Vercel deployment instructions
vuejs/vue-cli pull request #5835
Opened 2020-08-28 18:04 UTC by timothyis

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
This pull request updates the Vercel deployment documentation to match what Vercel recommends users can do to deploy for the greatest chance of success.

2020-09-12 12:12 UTC, gustawdaniel requested changes
The previous version was more concise and readable.

In my opinion docs of Vercel usage by the console should not be deleted, because of this project is `cli`.

2020-09-14 10:48 UTC, timothyis commented
Hi @gustawdaniel. The changes I've made makes it so users can set up a project with Vercel easily, then they can use Vercel CLI after if they'd like and we'll guide them to that. This change reflects the recommendation that Vercel is making ourselves.

2020-09-22 08:18 UTC, samsisle commented
Hi @gustawdaniel, is there any update to this?

2020-10-06 10:22 UTC, NataliaTepluhina approved these changes

2020-10-06 10:22 UTC, merged