types(vue.config.js): add descriptions for config
vuejs/vue-cli pull request #5967
Opened 2020-10-15 15:25 UTC by vegerot

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [x] Other, please describe: Config descriptions

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**
Personally, I have found it frustrating working with `vue.config.js`, due to lack of type information available.  Yesterday I discovered https://github.com/vuejs/vue-cli/issues/2138#issuecomment-484520356 , and was delighted to see I had a bit more info, but still not as much as I'd like.  

This commit adds JSDoc documentation (from `docs/config/README.md`) to add better editor support for `vue.config.js`

2020-10-30 03:00 UTC, fangbinwei requested changes
Thank you 😃, just a small problem

2020-10-30 14:07 UTC, vegerot commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   */
Fixed in 65a6148

2020-10-30 15:53 UTC, fangbinwei requested changes
Correct spelling

2020-10-30 15:53 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Set webpack configuration.  If the value is `Object`, will be merged into config.  If value is `Function`, will receicve current config as argument
```suggestion
   * Set webpack configuration.  If the value is `Object`, will be merged into config.  If value is `Function`, will receive current config as argument
```

2020-10-31 08:47 UTC, fangbinwei requested changes

2020-10-31 08:47 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `true`
```suggestion
   * Default: `false`
```

2020-10-31 08:47 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `true`
sourceMap is disabled by default

2020-11-02 02:35 UTC, fangbinwei approved these changes
Thanks a lot!

2020-11-02 03:19 UTC, fangbinwei requested changes

2020-11-02 03:19 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `'/'`
```suggestion
   * Default: `'/'`
   *
```

2020-11-02 03:19 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `'/'`
It seems adding a new line after all `Default`, the editor can give more friendly  parameter info.
![image](https://user-images.githubusercontent.com/13298807/97826468-9ad63d00-1cfc-11eb-8690-274f873bfff6.png)

If no new line, 
![image](https://user-images.githubusercontent.com/13298807/97826518-b6d9de80-1cfc-11eb-9a57-197501fbd237.png)

test by windows vscode

2020-11-02 05:45 UTC, fangbinwei requested changes

2020-11-02 05:45 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `default`
```suggestion
   * Default: `'default'`
```

2020-11-02 05:45 UTC, fangbinwei commented on packages/@vue/cli-service/types/ProjectOptions.d.ts
> +   * Default: `default`
single quotes for string

2020-11-02 15:08 UTC, fangbinwei approved these changes
Thanks a lot!

2020-11-02 15:13 UTC, merged