feat(eslint): support eslint7 and @babel/eslint-parser
vuejs/vue-cli pull request #6059
Opened 2020-11-15 20:58 UTC by fangbinwei

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**Other information:**
replace babel-eslint with @babel/eslint-parser, bump eslint to ^7.13.0

2020-11-16 00:07 UTC, fangbinwei commented
It seems `@vue/cli-plugin-eslint/lint.js` break in test, will check later.

2020-11-16 13:54 UTC, sodatea requested changes
`@babel/core` is a peer dependency of `@babel/eslint-parser`, we need to explicitly install it into the user project.
Implicitly depending on package hoisting may break some package managers.

2020-11-19 07:51 UTC, sodatea requested changes
Looks good. Now please merge from the dev branch. I just updated `yarn.lock `and now there's a merge conflict here.

2020-11-20 01:10 UTC, sodatea approved these changes

2020-11-20 01:10 UTC, merged