fix: use basic auth for npm registry access
vuejs/vue-cli pull request #6207
Opened 2021-01-12 16:05 UTC by bodograumann

When username and password are configured in the .npmrc for the
respective scope, use basic auth when getting package metadate from the
npm registry.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

Cf. https://github.com/vuejs/vue-cli/issues/6206

2021-01-12 16:05 UTC, bodograumann commented
This can also be cherry-picked on `v4`.

2021-01-13 08:08 UTC, bodograumann commented
What is the problem and why can I not see the test result myself?

2021-01-13 09:54 UTC, fangbinwei commented
Maybe you should log in `circleci` first 

I can see some errors like below
![image](https://user-images.githubusercontent.com/13298807/104436141-353de100-55c8-11eb-83a5-c1a6fce93c7d.png)

2021-01-13 11:46 UTC, sodatea requested changes

2021-01-13 11:46 UTC, sodatea commented on packages/@vue/cli/lib/util/ProjectPackageManager.js
> +    }
Missing `return` here

2021-01-13 12:48 UTC, bodograumann commented on packages/@vue/cli/lib/util/ProjectPackageManager.js
> +    }
Ah right. Thanks for the hint :-)

2021-01-13 12:50 UTC, bodograumann commented
@fangbinwei Thanks for the paste.
I don’t have a circlici account and when I try to create one, it asks for write-permissions to my github account.
So that is not an option for me.

2021-01-14 08:41 UTC, sodatea approved these changes

2021-01-14 08:42 UTC, merged