feat: Upgraded Nightwatch to 1.6.4, updated distribued config
vuejs/vue-cli pull request #6520
Opened 2021-06-07 13:15 UTC by vaibhavsingh97

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

2021-06-09 07:35 UTC, vaibhavsingh97 commented
I don't know why `ci/circleci: cli-ui` failed, as the changes are only related to nightwatch plugin

2021-06-24 15:43 UTC, vaibhavsingh97 commented
@sodatea can you please review, and let me know if there any changes required

2022-01-06 13:09 UTC, vaibhavsingh97 commented
@sodatea can you please review

2022-01-14 07:14 UTC, sodatea requested changes

2022-01-14 07:14 UTC, sodatea commented on packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.conf.js
> +    },
Cucumber-js example is not available in nightwatch 1.7, please remove this.

2022-02-07 08:38 UTC, sodatea commented on packages/@vue/cli-plugin-e2e-nightwatch/nightwatch.conf.js
> +    },
Never mind. I didn't read the title correctly. The problem is that the nightwatch version in the package.json isn't updated, the config is fine.

2022-02-07 10:57 UTC, sodatea approved these changes

2022-02-07 10:57 UTC, merged