fix: switch to @node-ipc/node-ipc
vuejs/vue-cli pull request #7063
Opened 2022-03-18 13:12 UTC by AaronDewes

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Underlying tools
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Other information:**

This pull request switches to [@node-ipc/node-ipc](https://www.npmjs.com/package/@node-ipc/node-ipc), a fork of node-ipc without malware.

2022-03-18 18:04 UTC, achrinza commented
Looks like there's another `node-ipc` fork as well. :P

Just for reference, I'm also maintaining my own fork here: https://github.com/achrinza/node-ipc/issues/1

2022-03-18 19:46 UTC, Sacramentix commented on packages/@vue/cli-shared-utils/lib/ipc.js
> +const ipc = require('@node-ipc/compat')
Meaby add a little comment explaning why the node ipc has been replace

2022-03-18 19:47 UTC, Sacramentix commented on packages/@vue/cli-ui/apollo-server/util/ipc.js
> +const ipc = require('@node-ipc/compat')
Meaby add a little comment here too explaning why the node ipc has been replace

2022-03-18 19:53 UTC, Sacramentix requested changes
Has a i said in comment, we could add a little comment explaining why the depedency has change.

2022-03-19 04:17 UTC, DumbGameMaker commented
@node-ipc/compat seems like just a backported version of node-ipc (@node-ipc/node-ipc) not a fork. I could be wrong though. If this is true, might be a better option to choose a third-party fork like achrinza's, because the author of node-ipc could add the patch to @node-ipc/compat

2022-03-19 15:05 UTC, achrinza commented
@DumbGameMaker They're all third-party forks of the original package `node-ipc` with different goals:

- **`@achrinza/node-ipc`:** Maintained by achrinza. Follows upstream closely. Drop-in replacement. No new features. 
    - **`@achrinza/node-ipc@9`:** Compatible fork of v9
    - **`@achrinza/node-ipc@10`:** Compatible fork of v10/v11
- **`@node-ipc/*`**: Maintained by AaronDewes. New features and enhancements such as TypeScript rewrite.
    - **`@node-ipc/compat@9`:** Compatible fork of v9
    - **`@node-ipc/node-ipc@11`:** Compatible fork of v10/v11

The [FAQ](https://github.com/achrinza/node-ipc/issues/1) provides more info on the difference.

2022-03-22 14:30 UTC, haoqunjiang commented
Hi, thank you for all the help here!

After reading the FAQ section by @achrinza and reviewing the two projects, I decided to use `@achrinza/node-ipc` for now. https://github.com/vuejs/vue-cli/commit/75826d6598e7c17f727a891432d1902b9f31db0e

It's not that the other fork isn't good.
But the drop-in replacement approach is easier for me to review:
https://github.com/achrinza/node-ipc/compare/84dce1b4b28ac4fc66179ee3dcd5bc6d6c1032f1...v9
https://github.com/node-ipc/node-ipc/compare/97f4f49b63130033e67deeac424e691a8cc33f8c...d805d592f4e3b963126baea69f52ced569f6252f

And Vue CLI doesn't need any new feature from `node-ipc` for now, so I've temporarily pinned the dependency version, too.

Thanks again!

2022-03-22 14:30 UTC, closed without merging